In [1]:
import pandas as pd

In [8]:
df = pd.read_excel("feedback_results.xlsx")
df.head()

,retrievedChunks,sessionId,messageId,consultedDocuments,modelAnswer,username,answerTimestamp,userQuestion,feedbackUpdatedAt,feedbackNote,point
0,"['{""system"":"" **Role:** You are the \\""TTKB Le...",772bd8e8-66e0-4a40-82db-061a4eafa345,0315f430-803c-45af-b877-f63ee1b78cc5,['s3://goaltech-poc-ai-assistant/gold/mevzuat....,Başkanlığın yabancı dil eğitimine yönelik spes...,admin,2026-02-23T10:51:07.453094+00:00,Talim ve Terbiye Kurulu Başkanlığı'nın yabancı...,NaN,NaN,NaN
1,['Hangi daire başkanlıkları kurul başkan yardı...,772bd8e8-66e0-4a40-82db-061a4eafa345,2a68ece5-77f3-4cfc-8de2-137365db2cde,['s3://goaltech-poc-ai-assistant/gold/09111225...,Talim ve Terbiye Kurulu Başkanlığı'nın organiz...,admin,2026-02-23T11:08:47.974188+00:00,Hangi daire başkanlıkları kurul başkan yardımc...,NaN,NaN,NaN
2,"['{""system"":"" **Role:** You are the \\""TTKB Le...",772bd8e8-66e0-4a40-82db-061a4eafa345,5509460f-ab2e-47fb-a231-9a44350a5773,['s3://goaltech-poc-ai-assistant/gold/09111225...,TTKB Kalite El Kitabı'ndaki organizasyon şemas...,admin,2026-02-23T11:10:10.558941+00:00,Hangi daire başkanlıkları kurul başkan yardımc...,NaN,NaN,NaN
3,"['{""system"":"" **Role:** You are the \\""TTKB Le...",772bd8e8-66e0-4a40-82db-061a4eafa345,77df51e9-2b41-4f98-9ca2-d902642a5c74,['s3://goaltech-poc-ai-assistant/gold/08151335...,"Üzgünüm, bana verilen kaynaklarda sorunuzun ce...",admin,2026-02-23T10:48:32.026357+00:00,Talim ve Terbiye Kurulu Başkanlığı tarafından ...,NaN,NaN,NaN
4,"['{""system"":"" **Role:** You are the \\""TTKB Le...",772bd8e8-66e0-4a40-82db-061a4eafa345,89f292a6-e8e9-474c-99cd-6ee9bbe63314,['s3://goaltech-poc-ai-assistant/gold/t5.01.do...,Talim ve Terbiye Kurulu Başkanlığı'nın organiz...,admin,2026-02-23T11:09:41.030566+00:00,Hangi daire başkanlıkları kurul başkan yardımc...,NaN,NaN,NaN

In [9]:
df.describe()

           point
count  48.000000
mean    7.229167
std     3.799438
min     0.000000
25%     5.000000
50%     9.000000
75%    10.000000
max    10.000000